name: Release new version

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Build zip files
      run: python ci_release.py
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
